apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: invio
spec:
  selector:
    app: ai-service
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
  type: ClusterIP
