apiVersion: v1
kind: Service
metadata:
  name: stock-service
  namespace: invio
spec:
  selector:
    app: stock-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
