#name: CD
#
#on:
#  push:
#    branches: [develop]
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#
#    env:
#      COMMIT_MSG: ${{ github.event.head_commit.message || 'no message' }}
#      BRANCH: ${{ github.ref_name }}
#      COMMIT_SHA: ${{ github.sha }}
#
#    steps:
#      - name: Notify deploy start
#        uses: actions/checkout@v6
#
#      - name: Notify start
#        uses: ./.github/actions/discord-notify
#        with:
#          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
#          title: "CD 시작"
#          color: 3447003
#          message: ${{ env.COMMIT_MSG }}
#          branch: ${{ env.BRANCH }}
#          sha: ${{ env.COMMIT_SHA }}
#
#      - name: Deploy to server
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          key: ${{ secrets.SERVER_SSH_KEY }}
#          script: |
#            cd /root/delivering
#            git pull origin develop
#            ./gradlew clean build -x test
#            docker compose up --build -d
#
#      - name: Notify success
#        if: success()
#        uses: ./.github/actions/discord-notify
#        with:
#          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
#          title: "CD 성공"
#          color: 5763719
#          message: ${{ env.COMMIT_MSG }}
#          branch: ${{ env.BRANCH }}
#          sha: ${{ env.COMMIT_SHA }}
#
#      - name: Notify failure
#        if: failure()
#        uses: ./.github/actions/discord-notify
#        with:
#          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
#          title: "CD 실패"
#          color: 15548997
#          message: ${{ env.COMMIT_MSG }}
#          branch: ${{ env.BRANCH }}
#          sha: ${{ env.COMMIT_SHA }}